# Generated by Django 4.2.2 on 2023-06-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                default="profile_pic/default.png", upload_to="profile_pic/"
            ),
        ),
    ]
