# Generated by Django 4.2.2 on 2023-06-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("featured_img", models.ImageField(upload_to="project_img/")),
                ("demo_link", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "source_link",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("vote_ratio", models.IntegerField(blank=True, default=0, null=True)),
                ("vote_count", models.IntegerField(blank=True, default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
